--- 
kind: pipeline
name: AzureClang
steps: 
  - 
    commands: 
      - "export PATH=/usr/bin/core_perl:$PATH"
      - "bash build-tc*"
    environment: 
      GITHUB_TOKEN: 
        from_secret: GITHUB_TOKEN
      TOKEN: 
        from_secret: token
    image: "panchajanya1999/archlinux:latest"
    name: Azure-Clang
    trigger: 
      branch: 
        - master
